Add audio API specs
aabounegm/cast pull request #113
Opened 2022-03-07 21:24 UTC by alkaitagi

Added 3 tests to cover recently updated audio API. Closes #102.

2022-03-07 21:46 UTC, illright commented on src/lib/entities/audio/specs/audio-instance.spec.ts
> +  it('load audio', () => {
nitpick (non-blocking): the code would read slightly better like this:
```suggestion
  it('loads audio', () => {
```

2022-03-07 23:52 UTC, aabounegm reviewed
I would recommend a few more tests, such as seeking to a negative time or beyond the audio duration

2022-03-08 07:56 UTC, illright commented on src/lib/entities/audio/specs/audio-instance.spec.ts
> +  it('load audio', () => {
I meant to do this for all `it()`-s :)

2022-03-08 10:23 UTC, alkaitagi commented
For some reason in tests audio loaing doesn't correctly set `duration`. I've rested it with logs in `npm run dev` and it works. Does the testing environment have no network connection?

2022-03-08 10:54 UTC, illright commented
The testing environment doesn't have a DOM at all, you're not mounting anything. I actually think it's for the best, and wherever you need internet or the DOM, I suggest you mock your way out of it

2022-03-08 10:56 UTC, illright requested changes

2022-03-08 10:56 UTC, illright commented on src/lib/entities/audio/specs/audio-instance.spec.ts
> +    await new Promise((r) => setTimeout(r, 1000));
issue: explicit hard-coded waits could lead to test flake and unnecessary slowdown of test execution

question: why do we need it? Can we mock stuff in order to remove the need for this wait?

2022-03-09 13:04 UTC, illright approved these changes

2022-03-09 17:08 UTC, merged

2022-03-09 17:09 UTC, alkaitagi commented
@illright for some reason the actions passes but the `build-and-test` is in "expected" mode and I can't merge.