Feature/persisting listening history
aabounegm/cast pull request #94
Opened 2022-03-05 05:51 UTC by VanishMax

Closes #58 

What it does and what it does not:
* Implements the play button in EpisodeCard
* Adds a `podcastId` prop to EpisodeCard to track listening history of podcasts, not episodes
* Stores listening history of 6 (at maximum) podcasts
* Doesn't work on Library page. Do we need it there, @illright?

2022-03-05 11:14 UTC, illright requested changes

2022-03-05 11:14 UTC, illright commented on src/lib/widgets/episode/ui/episode-card.svelte
> +  const playAudio = () => {
issue: I'm concerned that this duplicates the logic of `features/playback-controls/model/toggle-global-playback`

suggestion: could we edit that one instead and use it here?

2022-03-05 11:14 UTC, illright commented on src/lib/entities/audio/model/listening-history.ts
> +    return [podcastId, ...history.filter((id) => id === podcastId)].slice(0, 6);
question: Have you confirmed this works correctly? Looks like it should be a `!==` here

I'd appreciate if you added unit tests to your code as you write it, it's going to be quite a chore to add them later on

2022-03-05 11:15 UTC, illright commented
I'm not sure what do you mean by "doesn't work on the library page", or what a library page is, for that matter. We have a "Your Library" page which is supposed to only list favorites, not the history.

2022-03-06 12:16 UTC, VanishMax commented
> or what a library page is, for that matter

I meant that I didn't add tracking the history when listening to the podcast on the `/library` page. It has only the liked episodes without connection to podcasts. Therefore, I didn't manage to get the `podcastId` from episodes on `/library` page

2022-03-06 12:41 UTC, illright commented
Oh, okay. I think it's good enough for now

2022-03-06 16:01 UTC, VanishMax commented
@alkaitagi Everything is fixed, please check

2022-03-07 06:07 UTC, illright commented on src/lib/widgets/episode/ui/episode-card.svelte
> +    toggleGlobalPlayback();
issue: but now it won't know what audio to play.

suggestion: I think we should modify the `toggleGlobalPlayback` function to accept a URL

2022-03-07 11:47 UTC, alkaitagi commented
@alkaitagi I think you should merge from `main` because we've greatly simplified the audio API and it will help you.

2022-03-08 07:40 UTC, VanishMax commented
@illright you were totally correct with the audio not being played. I fixed that now, and sorry for the delay

2022-03-08 07:52 UTC, illright requested changes
Minor issue related to FSD isolation principles

2022-03-08 07:52 UTC, illright commented on src/lib/widgets/episode/ui/episode-card.svelte
> +  import { addToListeningHistory } from '$lib/entities/audio/model/listening-history';
issue: according to FSD, you cannot go inside a slice from another slice, you must stop at the `index.ts`:
```suggestion
  import { addToListeningHistory } from '$lib/entities/audio';
```

2022-03-08 07:52 UTC, illright commented on src/lib/widgets/episode/ui/episode-card.svelte
> +  import { toggleGlobalPlayback } from '$lib/features/playback-controls';
nitpick (non-blocking): this import could be merged with another import above from the same module

2022-03-08 10:30 UTC, alkaitagi approved these changes

2022-03-08 12:44 UTC, illright approved these changes

2022-03-08 12:48 UTC, merged